{% set name = "special_functions" %}
{% set data = load_setup_py_data() %}

package:
    name: "{{ name|lower }}"
    version: "{{ data['version'] }}"

source:
    path: ..

build:
    number: 0
    script: 
        # - {{ PYTHON }} -m pip install . -vv
        - {{ PYTHON }} setup.py install

requirements:
    build:
        - python                          # [build_platform != target_platform]
        - cython 0.29.21                  # [build_platform != target_platform]
        - numpy 1.19.2                    # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}       # [unix]

    host:
        - libcxx                          # [osx]
        - python {{ python }}
        - numpy 1.19.2
        - cython 0.29.21
        - pip 20.3.3
        - pytest 6.2.2
        - pytest-cov 2.11.1
        - scipy 1.6.0
        - setuptools 52.0.0
    run:
        - python {{ python }}

test:
    imports:
        - special_functions
    requires:
        - pytest
        - pytest-cov
        - scipy

about:
    home: {{ data['url'] }}
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: {{ data['description'] }}
    description: {{ data['description'] }}
    doc_url: https://ameli.github.io/special_functions/index.html
    doc_source_url: https://github.com/ameli/special_functions/blob/main/README.rst
    dev_url: https://github.com/ameli/special_functions

extra:
    recipe-maintainers:
        - ameli
