{% set name = "special_functions" %}
{% set data = load_setup_py_data() %}

package:
    name: "{{ name|lower }}"
    version: "{{ data['version'] }}"

source:
    path: ..

build:
    number: 0
    script: 
        # - {{ PYTHON }} -m pip install . -vv
        - {{ PYTHON }} setup.py install

requirements:
    build:
        - python                          # [build_platform != target_platform]
        - cython                          # [build_platform != target_platform]
        - numpy                           # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}       # [unix]

    host:
        - libcxx                          # [osx]
        - python {{ python }}
        - numpy>1.11
        - cython
        - pip
        - pytest
        - pytest-cov
        - scipy
        - setuptools
    run:
        - python {{ python }}

test:
    imports:
        - special_functions
    requires:
        - pytest
        - pytest-cov
        - scipy

about:
    home: {{ data['url'] }}
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: {{ data['description'] }}
    description: {{ data['description'] }}
    doc_url: https://ameli.github.io/special_functions/index.html
    doc_source_url: https://github.com/ameli/special_functions/blob/main/README.rst
    dev_url: https://github.com/ameli/special_functions

extra:
    recipe-maintainers:
        - ameli
