name: "Check Manifest"

on:
    push:
        branches:
            - main
    release:
        types: [published]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install cython
                  python -m pip install flake8
                  python -m pip install check-manifest

            - name: Check flake
              run: flake8

            - name: Check manifest
              run: check-manifest -v
