name: learn-github-actions-testing
on: [push]
jobs:
  build:
    runs-on: macos-latest-xlarge
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
